server.port=${PORT:8080}

spring.application.name=FinanceDashboard

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (recommended for MySQL stability)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT (mapped from ENV)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
